Ensure 3.5 compatibility
It looks like Python 3.5 requires the module names to be dotted.  Otherwise, it throws an error

```
...
from Porter import Porter
    ImportError: No module named 'Porter'
```